version: '3.8'

services:
  postgres:
    build:
        context: .
        dockerfile: Dockerfile
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
    ports:
      - 5432:5432
